name = "Mersenne31"
version = "0.1.0"
defaultTargets = ["Mersenne31"]

[[lean_lib]]
name = "Mersenne31"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"